### ISSUE TITLE
More tightly scoped `es-abstract` import

### ISSUE THREAD

**Issue by lencioni** [es-shims/String.prototype.matchAll#1]
I am working on bundling up some shims and one of our shims bundles targets browsers that support `<script type="module">`. While looking at what is getting bundled here, I noticed that the bulk of the weight comes from `es-abstract`, and that `string.prototype.matchall` is the only dependency that imports all of `es-abstract` instead of a smaller subset (e.g. `es-abstract/es2016`). 

![screen shot 2018-08-09 at 8 59 21 am](https://user-images.githubusercontent.com/195534/43910779-97982428-9bb2-11e8-972e-b70e5bd87133.png)

I'm wondering, is it possible for the `es-abstract` import to be scoped more tightly in this package?

**Comment by ljharb** [comment]
That’s not really a smaller subset tho - it’d have to import 2018, and that includes everything anyways.

I certainly will update it to use 2018 (i forget if I’ve published that or not) after the latest round of feedback on the proposal is settled.

**Comment by lencioni** [comment]
Ah, I see. I was thinking about it backwards. That's too bad, but oh well!

**Comment by ljharb** [comment]
This is achieved via es-abstract v1.17.0, and available in v4.0.1.
