### ISSUE TITLE
compiled shim?

### ISSUE THREAD

**Issue by mafar** [es-shims/String.prototype.matchAll#2]
IS there a compiled shim that I can use to make tests on jsfiddle etc

**Comment by ljharb** [comment]
https://wzrd.in/standalone/string.prototype.matchall@latest

**Comment by mafar** [comment]
I used above in jsfiddle and i get error 
 ```str.matchAll is not a function```
https://jsfiddle.net/bababalcksheep/o4qn7jwe/29/

**Comment by ljharb** [comment]
Because that’s a bundle for the main entry point, which doesn’t auto shim.

**Comment by mafar** [comment]
I just want to use/check matchAll  functionality to see if it can fullfill my needs .
Can a usable distributable be made ?

**Comment by ljharb** [comment]
Is there a reason you can’t click on the runkit link on the npm package page and try it there? All JS should only be consumed from npm anyways, so you might as well test it out as an npm package.
